[package]
name = "sip-message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reader = { path = "../reader" }
itertools = "0.13.0"

[dev-dependencies]
assert_matches = "1.5"
criterion = "0.5"