[package]
name = "sip"
version = "0.1.0"
edition = "2021"

[dependencies]
reader = { path = "../reader" }


[dev-dependencies]
assert_matches = "1.5"
criterion = "0.5"

[[bench]]
name = "bench"
harness = false
