[package]
name = "sip"
version = "0.1.0"
edition = "2021"

[dependencies]
lexical-core = "1.0.2"


[dev-dependencies]
assert_matches = "1.5"
criterion = "0.5"

[[bench]]
name = "parse"
harness = false
